spring:
    application:
        name: spring-practice-gateway

    cloud:
        gateway:
            mvc:
                routes:
                    -   id: spring-practice-rest-mvc
                        uri: http://localhost:8081
                        predicates:
                            - path= /api/v1/*
